#!/usr/bin/env python3
"""A Python function that returns the list of schools with a specific topic:
"""


def schools_by_topic(mongo_collection, topic):
    """Updates the topics field of all school documents in the
    specified collection with the given name.

    Args:
        mongo_collection (pymongo collection object): MongoDB collection
        topic (str): the topic searched

    Returns:
        A list of schools having a specific topic:
    """
    schools = mongo_collection.find(
        {"topic": topic},
    )
    return schools
